### ISSUE TITLE
Pro Con Streamer Theme

### ISSUE THREAD

**Issue by Tomshiii** [RetroWeeb/open-joystick-display#16]
_(I accidentally submitted this before with only a title that was not good oof)_
Didn't want to be a pain and come across as picky or annoying but with the addition of the joycon streamer theme I was wondering if it would be possible to add a pro con version?
Super mario odyssey speedrunners are starting to homebrew their switches to add input display and a large majority of us use procon, a slick streamer theme would be amazing.
I'd make one but I don't really have any knowledge what so ever relating to getting that started let alone making it look good. From my quick scouting I see you're busy with other things for this project so think of this as just a show of something that would be used by a lot and not trying to be a pest.

**Comment by RetroWeeb** [comment]
@Tomshiii I actually forgot to add it, I think this small fix is worthy of a patch since I see that the NX server software is gaining popularity. I'll try to get 2.5.1 out this evening and that will resolve your concerns.

**Comment by RetroWeeb** [comment]
@Tomshiii I got caught up yesterday, however it's done (screenshot) I'll get a build out this evening. Comes in the standard set of colors the other streamer colors come into. If you want I can build you a custom theme bundle you can modify the CSS colors to your liking. 

![Screenshot_2019-08-02_11-08-53](https://user-images.githubusercontent.com/46404303/62379909-ec9a8100-b515-11e9-9d97-22f9f8bbd6d3.png)

**Comment by Tomshiii** [comment]
If you could hit me up with something like that, that would be amazing, I could share that around the community. No rush at all though. This looks incredible btw!

**Comment by RetroWeeb** [comment]
@Tomshiii the theme is live on https://ojdproject.com/, 2.5.1 has your fixes. However I'm not going to close this ticket out yet, let me get you a custom theme bundle you can use and modify to your liking.

**Comment by RetroWeeb** [comment]
https://ojdproject.com/downloads/themes/custom-switch-streamer.zip

@Tomshiii  here is your custom theme pack template. It includes the same SVGs and CSS files as the OJD bundle however only pink and white and in its own namespace (both joycons and pro). 

**Installation:**
In the mapper sidebar simple point it to the themes folder that you have extracted from the ZIP file. Should show up under the user themes section of the theme dropdown.

**How to do modifications:**
I do recommend you read the developer guide here: https://ojdproject.com/developer-guide However I'll give you a quick todo:

To change the colors you can simply edit the color files. They are simple CSS selectors to change colors. If you want to add new colors or template make a new css file (like streamer-red.css) and add it to the theme.json file.

You can get pretty crazy with this and modify the SVGs to your liking. I recommend using inkscape since it will retain the mapping for the controller buttons as you move stuff around.

Play around with it and go crazy, send it off to your friends and see what they can do. All in all, it's open source and you're basically free to do as you wish with it.

If you're happy with all of this and got time please leave me a positive review on the OBS forums, it goes a long way. Thanks again for pointing out the missing streamer themes!
