### ISSUE TITLE
[Question] Open to Donations?

### ISSUE THREAD

**Issue by odysseywestra** [RetroWeeb/open-joystick-display#2]
It would be awesome if you add a Patron or just a Donation button so we can at least help ya with the server costs at least. I sure some twitch streamers would gladly support ya too.

**Comment by RetroWeeb** [comment]
Hey @odysseywestra thanks for reaching out! I originally had a Patreon but closed it because it didn't align well with me in regards to ideals of Open Joystick Display. Here is the exact notice I posted when I closed that feature:

> Why I'm closing the Patreon page is a different issue. I was conflicted at first at putting a donate button because it's free software but wanted to try it anyways. However, after having it up for a couple of months with only one backer (who which, by the way, _was my best friend_, who doesn't even use the application but wanted to support me) it's clear to me that having a donation isn't worth managing. The software is free and open source and will continue to be that way with no expectation of RoI.

So TL;DR there won't be any donation feature in the future. I appreciate the willingness to help, but have come to accept financial responsibility for the project.

I know It has been slow this last month with updates (personal stuff, moving to a new job, etc.), but my next release will have client-server communication (for those with a streaming and encoding PC) as well as some updated and/or new themes.

If you're looking to contribute, I am looking for help with new themes. If you look at the trello page (https://trello.com/b/ZJtrFKHD/open-joystick-display) there are some outstanding items for things like NeoGeo, GameGear, GameBoy, etc. If you or anyone else you know likes the application and would like to have them as part of the default package please send them my way and we can make that happen. Any and all that contribute will get credit on the about page and have their themes packaged with all releases in the future.

Anyways, thanks for reaching out, I'm glad you're enjoying OJD. If you have any more suggestions please don't hesitate to send them my way. :)

- Anthony
