### ISSUE TITLE
Open Joystick Display hogs CPU

### ISSUE THREAD

**Issue by AmenAnthem** [RetroWeeb/open-joystick-display#5]
After pressing a button Open Joystick Display starts using about 20% of my CPU while not having pressed a button it sits at 1%. It uses the most CPU out of any program on my PC by far.
If you need any further information let me know.

**Comment by RetroWeeb** [comment]
@AmenAnthem 

- What are the specs of your machine?
- Are you using the local gamepad (chromium), retrospy, or network driver?
- What operating system + version are you running?
- What version of OJD are you using?

Unfortunately I don't experience this issue myself and I use OJD nearly every day for my streams so some color on what your configuration is may help us figure out what the culprit is.

Thanks.

**Comment by AmenAnthem** [comment]
@RetroWeeb 

- CPU: i5-6500, 16GB RAM, GTX 960 4GB
- I'm using a local gamepad (Dualshock 4 controller wiith DS4Windows)
- Windows 10 Home 64 Bit Build 17134
- 2.2 64 Bit

**Comment by RetroWeeb** [comment]
@AmenAnthem I just happen to have that very processor + GPU configuration in the house in another computer. I will do some benchmarking and return. Sorry for the delayed response.

**Comment by RetroWeeb** [comment]
@AmenAnthem so I do see this on the i5- further research indicates it is because I have hardware acceleration disabled so that the application will work in OBS/XSplit in Windows (Linux and OSX does not have this issue but I have it disabled accross the board for support sake). If I enable HW acceleration the CPU usage cuts in half, however it renders black or transparent in OBS when using window capture (See this topic as to why: https://github.com/electron/electron/issues/16955). 

I could give the option to toggle HW acceleration and as a work around for this in OBS/XSplit you can capture via a second display and crop it when it's in broadcast mode- but unfortunately this is just a limitation of the framework being used right now and OBS/XSplit and electron.

**However, not all is lost:** you can cut your CPU usage in half (or even by a quarter) by upping the poll rate in the broadcast sidepanel. Bumping it to 20ms will cut CPU usage by over a half and not be very noticable, and even up to 30ms it's still very responsive for a joystick overlay.

Let me know if this will help you out- I'll be reaching out to OBS and figuring out when electron support will come for the future.

**Comment by AmenAnthem** [comment]
@RetroWeeb 
Thanks for looking at the issue.
Upping the polling rate did lower the CPU usage, unfortunately not by much.
Currently this is a workaround I can live with, I still prefer OJD to gamepadviewer.com because of the hardware accelaration issue. Having a viewer as a standalone app is more convinient :)
Please let me know if there are any news regarding this issue.

**Comment by RetroWeeb** [comment]
Thanks for following up! For now I will close this ticket, if anything changes I will make sure to add a comment here in the future.
