### ISSUE TITLE
Switch Problems...

### ISSUE THREAD

**Issue by PhoenixSMM** [RetroWeeb/open-joystick-display#9]
Honestly I don't know if this is fixable or if there's a way around this. This is probably not the right place to put this either... but I would appreciate it if you can help me in any way :) 
I have done a few speedruns of SMB Any% on my Nintendo Switch, and I would like to have input display with it. I can connect my Switch Pro Controller to my Laptop, and OJD works fine... except I can't get the D-Pad to work.
Anyway I'm wondering if it's possible, somehow, to connect my controller to both the Switch and the Laptop simultaneously. I can connect the controller with and without a lead to both devices, but at the same time... help? :D
![2019-07-10 (4)](https://user-images.githubusercontent.com/51673990/60999599-6f834e00-a353-11e9-8426-602c569c5e49.png)

**Comment by RetroWeeb** [comment]
Technically not possible on the dual-connection unfortunately because of the way both USB and/or Bluetooth works. However, I am in the process of working with one of the developers with the Switch hacking community to be able to send joycon/input commands over the network via your switch. But that will come later.

In regards to using just straight USB for your Switch Pro controller the d-pad doesn't work out of the box. There is an alternative driver you need to use for it (some options: https://www.pcmag.com/article/363239/how-to-use-a-nintendo-switch-pro-controller-on-a-pc)- this is the same same for the Pokken controller as well (which I highly suggest if you're doing SMB or MM and want a good d-pad).

I hope that helps, I've got a big update to the system coming out in a month or two so keep an eye out.

Thanks!

**Comment by PhoenixSMM** [comment]
Thank you! :D

**Comment by PhoenixSMM** [comment]
Thanks for the help! Really good to know. 
However, the link doesn't work for me...

**Comment by RetroWeeb** [comment]
@PhoenixSMM let me see if I can get a video on how to configure it. I'm mostly a Linux guy and the Pro Controllers and the Pokken controllers work fine over here in Linux land. I'll get back to you and see. Also with the latest version of OJD I released some Pro Controller themes so check them out if you're looking for some switch stuff.

**Comment by RetroWeeb** [comment]
@PhoenixSMM 
Try this new build of OJD: https://drive.google.com/file/d/1OWtDJeWZd28Pn6Rxfe3A-XIu1JZDAgpE/view?usp=sharing

And here are some video instructions (they were for someone else, but with a very similar issue- just follow along):
https://www.youtube.com/watch?v=8CgaSgfpzSE&feature=youtu.be

**Comment by RetroWeeb** [comment]
This has gone live, please download the latest stable (2.4) from the website. For now I will close this ticket, if it helps you please let me know. Thanks!
